CI: another attempt to install xfitter deps only

diff --git a/tools/install-xfitter b/tools/install-xfitter
--- a/tools/install-xfitter
+++ b/tools/install-xfitter
@@ -69,15 +69,19 @@ if [[ $mode != "deps" ]]
 else
     if [[ ! -e version ]]
         then
-        echo
-        echo "could not find file \"version\""
-        echo "cannot determine current version"
-        echo "run first:"
-        echo "$0 <version>"
-        echo
-        exit
+        # assume it is master (e.g. for gitlab CI)
+        version="master"
+        #
+        #echo
+        #echo "could not find file \"version\""
+        #echo "cannot determine current version"
+        #echo "run first:"
+        #echo "$0 <version>"
+        #echo
+        #exit
+    else
+        version=`cat version`
     fi
-    version=`cat version`
     echo "reinstalling dependencies for xFitter version $version"
 fi
 # strip the xfitter version
@@ -131,14 +135,14 @@ then
     echo
     exit
 fi
-if [[ $mode == "deps" && ! -e xfitter-${version}  && ! -e herafitter-${version}  ]]
-then
-    echo
-    echo "xfitter-${version} or herafitter-${version}   does not exist, install it first with:"
-    echo "$0 $version"
-    echo
-    exit
-fi
+#if [[ $mode == "deps" && ! -e xfitter-${version}  && ! -e herafitter-${version}  ]]
+#then
+#    echo
+#    echo "xfitter-${version} or herafitter-${version}   does not exist, install it first with:"
+#    echo "$0 $version"
+#    echo
+#    exit
+#fi
 
 #automatically detect system:
 if [[ -z $MANUALCONF ]]
@@ -591,8 +595,8 @@ then
         rm -fr xfitter-${version}
         mkdir xfitter-${version} ; tar xfz xfitter-${version}.tar.gz -C xfitter-${version} --strip-components 1
     fi
-else
-    make -C xfitter-${version} clean >> $CURRENTDIR/install.log  2>&1
+#else
+#    make -C xfitter-${version} clean >> $CURRENTDIR/install.log  2>&1
 fi
 
 
@@ -644,7 +648,10 @@ echo export PATH=\$CURRENTDIR/deps/apfel/bin/:\$PATH     >> compile
 echo export PATH=\$CURRENTDIR/deps/mela/bin/:\$PATH     >> compile
 
 
-echo cd xfitter-\$version                                        >> compile
+if [[ $mode != "deps" ]]
+then
+  echo cd xfitter-\$version                                        >> compile
+fi
 
 # check for YAML
 # xfitter 2.0.0 and 2.0.1 do not need YAML
@@ -671,7 +678,7 @@ if [[ $version != "2.0.0" ]] && [[ $version != "2.0.1" ]]; then
   else
     echo "YAMLCPP no" >> $CURRENTDIR/install.log
   fi
-  #rm -f test-tmp.cc
+  rm -f test-tmp.cc
   rm -f test-tmp.o
 
   if [ $HAVEYAML -eq 0 ] || [ $HAVEYAMLCPP -eq 0 ]; then
@@ -682,24 +689,26 @@ if [[ $version != "2.0.0" ]] && [[ $version != "2.0.1" ]]; then
   fi
 fi
 
-# configure
-if [[ $version == "2.0.0" ]] || [[ $version == "2.0.1" ]]; then
-  echo autoreconf --install                                 >> compile
-  echo ./configure --enable-applgrid --enable-lhapdf --enable-apfel --enable-apfelxx --enable-mela  --enable-apfelgrid --enable-process    >> compile
-  echo make -j 9 install                                    >> compile
-elif [[ $version == "master_before_PionCeres_merge" ]] || [[ $version == "test_ceres_v0.01" ]]; then
-  # SZ 10.07.2019 apfelgrid produces linking error in PionCeres
-  echo ./configure --enable-applgrid --enable-lhapdf --enable-hathor --enable-apfel --enable-apfelxx --enable-mela --enable-process    >> compile
-  echo make -j 9 install                                    >> compile
-  echo autoreconf --install                                 >> compile
-else
-  # cmake compilation
-  echo ./make.sh install >> compile
-fi
-
-
 chmod +x compile
-echo "Compiling xFitter $version..."
+
+# configure
+if [[ $mode != "deps" ]]
+then
+  if [[ $version == "2.0.0" ]] || [[ $version == "2.0.1" ]]; then
+    echo autoreconf --install                                 >> compile
+    echo ./configure --enable-applgrid --enable-lhapdf --enable-apfel --enable-apfelxx --enable-mela  --enable-apfelgrid --enable-process    >> compile
+    echo make -j 9 install                                    >> compile
+  elif [[ $version == "master_before_PionCeres_merge" ]] || [[ $version == "test_ceres_v0.01" ]]; then
+    # SZ 10.07.2019 apfelgrid produces linking error in PionCeres
+    echo ./configure --enable-applgrid --enable-lhapdf --enable-hathor --enable-apfel --enable-apfelxx --enable-mela --enable-process    >> compile
+    echo make -j 9 install                                    >> compile
+    echo autoreconf --install                                 >> compile
+  else
+    # cmake compilation
+    echo ./make.sh install >> compile
+  fi
+  echo "Compiling xFitter $version..."
+fi
 
 ./compile >> $CURRENTDIR/install.log  2>&1
 if [[ $? != 0 ]]
@@ -708,60 +717,63 @@ then
     exit
 fi
 
-# run test
 source ./setup.sh
-cd xfitter-${version}
 
-bin/xfitter >> $CURRENTDIR/install.log  2>&1
-
-
-
-if [[ $? != 0 ]]
+if [[ $mode == "deps" ]]
 then
-    echo "Error in testing xfitter executable, check install.log for details"
-    exit
-fi
-cd - >& /dev/null
-echo "xFitter installation successful!"
-echo "Check install.log file for details"
-echo
-# setup a run dir
-if [[ ! -e run ]]
-then
-    mkdir -p run
-    cp  xfitter-${version}/steering.txt \
-        xfitter-${version}/parameters.yaml \
-        xfitter-${version}/constants.yaml \
-        run
-    rsync -a --exclude=".*" xfitter-${version}/datafiles run/
-    rsync -a --exclude=".*" xfitter-${version}/theoryfiles run/
+  echo "Installing xfitter dependencies is complete"
+  echo "Check install.log file for details"
 else
-    echo "\"run\" directory already exists, I won't touch it"
-    echo
-fi
+  # run test
+  cd xfitter-${version}
+  bin/xfitter >> $CURRENTDIR/install.log  2>&1
 
-#quick start guide
-if [[ ! -e quickstart-readme.txt ]]
-then
-    echo "for a quick start do:" >> quickstart-readme.txt
-    echo >> quickstart-readme.txt
-    echo "source setup.sh #setup environment" >> quickstart-readme.txt
-    echo "cd run          #enter your run directory" >> quickstart-readme.txt
-    echo "xfitter          #run your fit" >> quickstart-readme.txt
-    echo >> quickstart-readme.txt
-    echo "The fit options are controlled by the 3 files steering.txt, parameters.yaml, and constants.yaml" >> quickstart-readme.txt
-    echo "Data and theory files are in datafiles directory" >> quickstart-readme.txt
-    echo >> quickstart-readme.txt
-    echo "After the fit, display you results with:" >> quickstart-readme.txt
-    echo "xfitter-draw output/" >> quickstart-readme.txt
-    echo "A file output/plots.pdf will be created" >> quickstart-readme.txt
-    echo "You can find further documentation in xfitter-$version/README and xfitter-$version/doc/tex/manual/" >> quickstart-readme.txt
-    echo "-----------------------------------------------------------"
-    cat quickstart-readme.txt
-    echo "-----------------------------------------------------------"
-    echo
-    echo "To read again these instructions, see quickstart-readme.txt"
-    echo "Have fun!"
-fi
+  if [[ $? != 0 ]]
+  then
+      echo "Error in testing xfitter executable, check install.log for details"
+      exit
+  fi
+  cd - >& /dev/null
+  echo "xFitter installation successful!"
+  echo "Check install.log file for details"
+  echo
+  # setup a run dir
+  if [[ ! -e run ]]
+  then
+      mkdir -p run
+      cp  xfitter-${version}/steering.txt \
+          xfitter-${version}/parameters.yaml \
+          xfitter-${version}/constants.yaml \
+          run
+      rsync -a --exclude=".*" xfitter-${version}/datafiles run/
+      rsync -a --exclude=".*" xfitter-${version}/theoryfiles run/
+  else
+      echo "\"run\" directory already exists, I won't touch it"
+      echo
+  fi
 
+  #quick start guide
+  if [[ ! -e quickstart-readme.txt ]]
+  then
+      echo "for a quick start do:" >> quickstart-readme.txt
+      echo >> quickstart-readme.txt
+      echo "source setup.sh #setup environment" >> quickstart-readme.txt
+      echo "cd run          #enter your run directory" >> quickstart-readme.txt
+      echo "xfitter          #run your fit" >> quickstart-readme.txt
+      echo >> quickstart-readme.txt
+      echo "The fit options are controlled by the 3 files steering.txt, parameters.yaml, and constants.yaml" >> quickstart-readme.txt
+      echo "Data and theory files are in datafiles directory" >> quickstart-readme.txt
+      echo >> quickstart-readme.txt
+      echo "After the fit, display you results with:" >> quickstart-readme.txt
+      echo "xfitter-draw output/" >> quickstart-readme.txt
+      echo "A file output/plots.pdf will be created" >> quickstart-readme.txt
+      echo "You can find further documentation in xfitter-$version/README and xfitter-$version/doc/tex/manual/" >> quickstart-readme.txt
+      echo "-----------------------------------------------------------"
+      cat quickstart-readme.txt
+      echo "-----------------------------------------------------------"
+      echo
+      echo "To read again these instructions, see quickstart-readme.txt"
+      echo "Have fun!"
+  fi
+fi
 
