Install script with pineappl and rust deps

diff --git a/tools/install-xfitter b/tools/install-xfitter
--- a/tools/install-xfitter
+++ b/tools/install-xfitter
@@ -3,7 +3,7 @@
 ## Configuration ####################################################
 
 ## Programs versions
-lhapdfver=6.5.3
+lhapdfver=6.5.1
 hathorver=2.0
 hoppetver=1.2.0
 applgridver=1.6.32
@@ -12,10 +12,14 @@ apfelver=3.0.6
 apfelgridver=1.0.5
 apfelxxver=4.0.0
 dyturbover=1.2
+pineapplver=0.5.8
+rustver=1.65.0
 
 # skip some packages depending on xfitter version
 skip_apfelgrid=0
 skip_dyturbo=1
+skip_rust=0
+skip_pineappl=0
 
 ## Optional manual configurations
 #MANUALCONF=1
@@ -147,6 +151,8 @@ then
     if [[ $? == 0 ]]
     then
         echo "Detected Mac OS X system"
+        rusttag="apple-darwin"
+        # TODO is there a mac command to check "arch" as in "Ubuntu" case below? Needed for rust.
         MODE=local
     else
         SYS=$(echo `lsb_release -i |cut -d: -f2`)
@@ -163,6 +169,7 @@ then
             rootversion=5.34.36
             boostver=1.53.0
             pyth=2.7
+            rusttag="unknown-linux-gnu"
         elif [[ $SYS == CentOS* && $ver == 7.* ]]
         then
             echo "Detected CentOS7 Linux distribution"
@@ -174,9 +181,15 @@ then
             rootversion=6.06.08
             boostver=1.53.0
             pyth=2.7
+            rusttag="unknown-linux-gnu"
         elif [[ $SYS == "Ubuntu" ]]
         then
             echo "Detected Ubuntu distribution"
+            rusttag="unknown-linux-gnu"
+            if arch==""
+            then
+                arch=`uname -m`
+            fi
             MODE=local
         elif [[ -e /cvmfs/sft.cern.ch ]]
 	then
@@ -593,8 +606,58 @@ else
       fi
       cd - >& /dev/null
     fi
-fi
+    
+ # rust:
+    if [[ $skip_rust != 1 ]]; then
+        echo "Installing Rust $rustver..."
+        
+        rust_url=https://static.rust-lang.org/dist/rust-${arch}-${rusttag}.tar.gz
+        if [[ $http == "curl" ]]
+        then
+            curl ${rust_url} > rust-${rustver}-${arch}-${rusttag}.tar.gz 2>> $CURRENTDIR/install.log
+        else
+            wget --no-check-certificate ${rust_url} >> $CURRENTDIR/install.log 2>&1
+        fi
+        tar xzf rust-${rustver}-${arch}-${rusttag}.tar.gz >> $CURRENTDIR/install.log  2>&1
+        cd rust-${rustver}-${arch}-${rusttag}
+        ./install.sh --prefix=$CURRENTDIR/deps/rust
+        export PATH=$CURRENTDIR/deps/rust/bin:$PATH
+        export LD_LIBRARY_PATH=$CURRENTDIR/deps/rust/lib/:$LD_LIBRARY_PATH
+        
+        # cargo-c needed for pineappl c-interface
+        echo "Installing cargo-c..."
+        cargo install cargo-c
+        if [[ $? != 0 ]]
+        then
+            echo "Error, check install.log for details"
+            exit
+        fi
+        export CARGODIR=$HOME/.cargo
+        export PATH=$CARGODIR/bin:$PATH 
+    fi
+    
+# pineappl:
+    if [[ $skip_pineappl != 1 ]]; then
+        echo "Installing PineAPPL $pineapplver..."
+          
+        PINEAPPL_URL=https://github.com/NNPDF/pineappl.git
+        git clone --branch  "v$pineapplver" $PINEAPPL_URL >> $CURRENTDIR/install.log 2>&1
+        cd pineappl/pineappl_capi
+        cargo cinstall --release --prefix=$CURRENTDIR/deps/pineappl
+        if [[ $? != 0 ]]
+        then
+            echo "Error, check install.log for details"
+            exit
+        fi
+        cd - >& /dev/null
+        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$CURRENTDIR/deps/lhapdf/lib/pkgconfig
+        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$CURRENTDIR/deps/pineappl/lib/pkgconfig
+        export LD_LIBRARY_PATH=$CURRENTDIR/deps/pineappl/lib:$LD_LIBRARY_PATH
+    fi
+
+    fi
 cd $CURRENTDIR
+
 
  #xfitter
 if [[ $mode != "deps" ]]
@@ -626,19 +689,27 @@ fi
 echo $version > version
 echo "export CURRENTDIR=`pwd`" >> setup.sh
 echo "export version=\`cat version\`" >> setup.sh
-echo "export PATH=$CURRENTDIR/xfitter-$version/bin:\$PATH" >> setup.sh
-echo "export PATH=$CURRENTDIR/deps/hoppet/bin:\$PATH" >> setup.sh
-echo "export PATH=$CURRENTDIR/deps/applgrid/bin:\$PATH" >> setup.sh
-echo "export PATH=$CURRENTDIR/deps/lhapdf/bin:\$PATH" >> setup.sh
-echo "export PATH=$CURRENTDIR/deps/apfel/bin:\$PATH" >> setup.sh
-echo "export PATH=$CURRENTDIR/deps/mela/bin:\$PATH" >> setup.sh
-echo "export PATH=$CURRENTDIR/deps/apfelxx/bin:\$PATH" >> setup.sh
-echo "export PATH=$CURRENTDIR/deps/dyturbo-${dyturbover}/bin:\$PATH" >> setup.sh
+echo export CARGODIR=\$HOME/.cargo                                  >> setup.sh
+echo export PATH=\$CURRENTDIR/xfitter-$version/bin:\$PATH           >> setup.sh
+echo export PATH=\$CURRENTDIR/deps/hoppet/bin:\$PATH                >> setup.sh
+echo export PATH=\$CURRENTDIR/deps/applgrid/bin:\$PATH              >> setup.sh
+echo export PATH=\$CURRENTDIR/deps/lhapdf/bin:\$PATH                >> setup.sh
+echo export PATH=\$CURRENTDIR/deps/apfel/bin:\$PATH                 >> setup.sh
+echo export PATH=\$CURRENTDIR/deps/mela/bin:\$PATH                  >> setup.sh
+echo export PATH=\$CURRENTDIR/deps/apfelxx/bin:\$PATH               >> setup.sh
+echo export PATH=\$CURRENTDIR/deps/dyturbo-${dyturbover}/bin:\$PATH >> setup.sh
+echo export PATH=\$CURRENTDIR/deps/rust/bin:\$PATH                  >> setup.sh
+echo export PATH=\$CARGODIR/bin:\$PATH                              >> setup.sh 
+echo export PATH=\$CURRENTDIR/deps/qcdnum/bin:\$PATH                >> setup.sh
 
 echo `lhapdf-config --prefix`/lib*/python*/site-packages > /tmp/xf_py1234_a
 echo "export PYTHONPATH=$PYTHONPATH:`cat /tmp/xf_py1234_a` " >> setup.sh
 rm /tmp/xf_py1234_a
 
+echo export PKG_CONFIG_PATH=\$PKG_CONFIG_PATH:\$CURRENTDIR/deps/lhapdf/lib/pkgconfig   >> setup.sh
+echo export PKG_CONFIG_PATH=\$PKG_CONFIG_PATH:\$CURRENTDIR/deps/pineappl/lib/pkgconfig >> setup.sh
+
+echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/pineappl/lib:\$LD_LIBRARY_PATH  >> setup.sh
 echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/hoppet/lib/:\$LD_LIBRARY_PATH   >> setup.sh
 echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/lhapdf/lib/:\$LD_LIBRARY_PATH   >> setup.sh
 echo export HATHOR_DIR=$CURRENTDIR/deps/Hathor-${hathorver}       >> setup.sh
@@ -647,8 +718,8 @@ echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/apfel/lib/:\$LD_LIBRARY_PATH >> se
 echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/mela/lib/:\$LD_LIBRARY_PATH >> setup.sh
 echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/qcdnum/lib/:\$LD_LIBRARY_PATH >> setup.sh
 echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/dyturbo-${dyturbover}/lib/:\$LD_LIBRARY_PATH >> setup.sh
-echo "export PATH=$CURRENTDIR/deps/qcdnum/bin:\$PATH" >> setup.sh
-
+echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/rust/lib/:\$LD_LIBRARY_PATH              >> setup.sh
+echo export LD_LIBRARY_PATH=\$CURRENTDIR/deps/pineappl/lib:\$LD_LIBRARY_PATH           >> setup.sh
 
 if [[ $MODE == "cern" ]]
 then
