wip install pineappl via install script

diff --git a/tools/install-xfitter b/tools/install-xfitter
--- a/tools/install-xfitter
+++ b/tools/install-xfitter
@@ -163,6 +163,8 @@ then
     then
         echo "Detected EL9 Linux distribution"
         MODE=local
+        #arch=x86_64
+        #rusttag="unknown-linux-gnu"
         #skip_rust=0
         #skip_pineappl=0
     else
@@ -196,6 +198,7 @@ then
         elif [[ $SYS == "Ubuntu" ]]
         then
             echo "Detected Ubuntu distribution"
+            skip_pineappl=0
             rusttag="unknown-linux-gnu"
             if [[ $arch == "" ]]
             then
@@ -255,7 +258,6 @@ if [[ $skip_pineappl == 0 ]] && [[ pineappl_lite == 1 ]]; then
         skip_rust=0
     fi
 fi
-
 
 if [[ $MODE == "cern" ]]
     then
@@ -339,6 +341,64 @@ else
     rm -rf deps >& /dev/null
     mkdir deps
     cd deps
+
+ # rust
+    if [[ $skip_rust == 0 ]]; then
+        echo "Installing Rust $rustver..."
+        rust_url=https://static.rust-lang.org/dist/rust-${rustver}-${arch}-${rusttag}.tar.gz
+        if [[ $http == "curl" ]]
+        then
+            curl ${rust_url} > rust-${rustver}-${arch}-${rusttag}.tar.gz 2>> $CURRENTDIR/install.log
+        else
+            wget --no-check-certificate ${rust_url} >> $CURRENTDIR/install.log 2>&1
+        fi
+        tar xzf rust-${rustver}-${arch}-${rusttag}.tar.gz >> $CURRENTDIR/install.log  2>&1
+        cd rust-${rustver}-${arch}-${rusttag}
+        ./install.sh --prefix=$CURRENTDIR/deps/rust
+        export PATH=$CURRENTDIR/deps/rust/bin:$PATH
+        export LD_LIBRARY_PATH=$CURRENTDIR/deps/rust/lib/:$LD_LIBRARY_PATH
+        
+        # cargo-c needed for pineappl c-interface
+        echo "Installing cargo-c..."
+        cargo install --version ${cargocver} cargo-c
+        if [[ $? != 0 ]]
+        then
+            echo "Error, check install.log for details"
+            exit
+        fi
+        cd - >& /dev/null
+        export CARGODIR=$HOME/.cargo
+        export PATH=$CARGODIR/bin:$PATH 
+    fi
+    
+ # pineappl:
+    if [[ $skip_pineappl == 0 ]]; then
+        echo "Installing PineAPPL $pineapplver..."
+        
+        if [[ $pineappl_lite == 1 ]]; then
+            mkdir $CURRENTDIR/deps/pineappl
+            PINEAPPL_URL=https://github.com/NNPDF/pineappl/releases/download
+            wget --no-check-certificate "${PINEAPPL_URL}"/v${pineapplver}/pineappl_capi-${arch}-${rusttag}.tar.gz -O- 2>> $CURRENTDIR/install.log | tar xzf - -C "$CURRENTDIR/deps/pineappl"
+            sed -i s:prefix=/:prefix=$CURRENTDIR/deps/pineappl: "$CURRENTDIR/deps/pineappl"/lib/pkgconfig/pineappl_capi.pc            
+        else
+            PINEAPPL_URL=https://github.com/NNPDF/pineappl.git
+            git clone --branch  "v$pineapplver" $PINEAPPL_URL >> $CURRENTDIR/install.log 2>&1
+            cd pineappl/pineappl_capi
+            cargo cinstall --release --prefix=$CURRENTDIR/deps/pineappl
+            if [[ $? != 0 ]]
+            then
+                echo "Error, check install.log for details"
+                exit
+            fi
+          cd - >& /dev/null
+        fi
+                
+        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$CURRENTDIR/deps/lhapdf/lib/pkgconfig
+        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$CURRENTDIR/deps/pineappl/lib/pkgconfig
+        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURRENTDIR/deps/pineappl/lib
+    fi
+    #exit 1
+
 #lhapdf:
     echo "Installing LHAPDF $lhapdfver..."
     if (( `echo $lhapdfver |cut -d. -f1` >= 6 ))
@@ -355,9 +415,9 @@ else
     else
         wget --no-check-certificate https://lhapdf.hepforge.org/downloads/${lhapdf}-${lhapdfver}.tar.gz >> $CURRENTDIR/install.log 2>&1
     fi
-    cat $CURRENTDIR/install.log
+    #cat $CURRENTDIR/install.log
     tar xfz ${lhapdf}-${lhapdfver}.tar.gz  >> $CURRENTDIR/install.log 2>&1
-    cat $CURRENTDIR/install.log 
+    #cat $CURRENTDIR/install.log 
     cd ${lhapdf}-${lhapdfver}
     ./configure --prefix=$CURRENTDIR/deps/lhapdf --disable-python  >> $CURRENTDIR/install.log  2>&1
     if [[ $? != 0 ]]
@@ -643,62 +703,6 @@ else
       cd - >& /dev/null
     fi
     
- # rust
-    if [[ $skip_rust == 0 ]]; then
-        echo "Installing Rust $rustver..."
-        rust_url=https://static.rust-lang.org/dist/rust-${rustver}-${arch}-${rusttag}.tar.gz
-        if [[ $http == "curl" ]]
-        then
-            curl ${rust_url} > rust-${rustver}-${arch}-${rusttag}.tar.gz 2>> $CURRENTDIR/install.log
-        else
-            wget --no-check-certificate ${rust_url} >> $CURRENTDIR/install.log 2>&1
-        fi
-        tar xzf rust-${rustver}-${arch}-${rusttag}.tar.gz >> $CURRENTDIR/install.log  2>&1
-        cd rust-${rustver}-${arch}-${rusttag}
-        ./install.sh --prefix=$CURRENTDIR/deps/rust
-        export PATH=$CURRENTDIR/deps/rust/bin:$PATH
-        export LD_LIBRARY_PATH=$CURRENTDIR/deps/rust/lib/:$LD_LIBRARY_PATH
-        
-        # cargo-c needed for pineappl c-interface
-        echo "Installing cargo-c..."
-        cargo install --version ${cargocver} cargo-c
-        if [[ $? != 0 ]]
-        then
-            echo "Error, check install.log for details"
-            exit
-        fi
-        cd - >& /dev/null
-        export CARGODIR=$HOME/.cargo
-        export PATH=$CARGODIR/bin:$PATH 
-    fi
-    
- # pineappl:
-    if [[ $skip_pineappl == 0 ]]; then
-        echo "Installing PineAPPL $pineapplver..."
-        
-        if [[ $pineappl_lite == 1 ]]; then
-            mkdir $CURRENTDIR/deps/pineappl
-            PINEAPPL_URL=https://github.com/NNPDF/pineappl/releases/download
-            wget --no-check-certificate "${PINEAPPL_URL}"/v${pineapplver}/pineappl_capi-${arch}-${rusttag}.tar.gz -O- | tar xzf - -C "$CURRENTDIR/deps/pineappl"
-            sed -i s:prefix=/:prefix=$CURRENTDIR/deps/pineappl: "$CURRENTDIR/deps/pineappl"/lib/pkgconfig/pineappl_capi.pc            
-        else
-            PINEAPPL_URL=https://github.com/NNPDF/pineappl.git
-            git clone --branch  "v$pineapplver" $PINEAPPL_URL >> $CURRENTDIR/install.log 2>&1
-            cd pineappl/pineappl_capi
-            cargo cinstall --release --prefix=$CURRENTDIR/deps/pineappl
-            if [[ $? != 0 ]]
-            then
-                echo "Error, check install.log for details"
-                exit
-            fi
-        fi
-        
-        cd - >& /dev/null
-        
-        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$CURRENTDIR/deps/lhapdf/lib/pkgconfig
-        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$CURRENTDIR/deps/pineappl/lib/pkgconfig
-        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURRENTDIR/deps/pineappl/lib
-    fi
 
 
     if [[ $skip_ploughshare == 0 ]]; then
