install dyturbo

diff --git a/tools/install-xfitter b/tools/install-xfitter
--- a/tools/install-xfitter
+++ b/tools/install-xfitter
@@ -11,6 +11,7 @@ qcdnumver=18-00-00
 apfelver=3.0.6
 apfelgridver=1.0.5
 apfelxxver=4.0.0
+dyturbover=1.2
 
 # skip some packages depending on xfitter version
 skip_apfelgrid=0
@@ -509,6 +510,34 @@ else
     fi
     cd - >& /dev/null
 
+ #dyturbo
+    echo "Installing DYTurbo ${dyturbover}..."
+    if [[ $http == "curl" ]]
+    then
+	curl https://dyturbo.hepforge.org/downloads?f=dyturbo-${dyturbover}beta.tar.gz > dyturbo-${dyturbover}.tar.gz 2>> $CURRENTDIR/install.log
+    else
+	wget https://dyturbo.hepforge.org/downloads?f=dyturbo-${dyturbover}beta.tar.gz >> $CURRENTDIR/install.log 2>&1
+    fi
+    tar xfz dyturbo-${dyturbover}.tar.gz  >> $CURRENTDIR/install.log  2>&1
+    cd dyturbo-${dyturbover}
+
+    ./configure --enable-Ofast  >> $CURRENTDIR/install.log  2>&1
+    export PATH=$CURRENTDIR/deps/dyturbo/bin/:$PATH
+
+    if [[ $? != 0 ]]
+    then
+        echo "Error, check install.log for details"
+        exit
+    fi
+    make -j 9 install  >> $CURRENTDIR/install.log  2>&1
+    if [[ $? != 0 ]]
+    then
+        echo "Error, check install.log for details"
+        exit
+    fi
+    cd - >& /dev/null
+    
+    
   # numdiff
     numdiff -v >& /dev/null
     if [[ `echo $?` != "0" ]]; then
